import streamlit as st
import requests

# Define the ngrok URL
url = "https://24ed-35-240-209-4.ngrok-free.app/verify_and_check_bias"

# Streamlit app
st.title("AI vs Human Text Classification")
st.write("Enter a text to test whether it is generated by AI or a human.")

# Input text box
input_text = st.text_area("Input Text", height=200)
ai_score_threshold = st.slider("AI Score Threshold", 0.0, 1.0, 0.5)

if st.button("Classify"):
    if input_text:
        # Define the input data for AI classification
        input_data = {
            "text": input_text,
            "ai_score_threshold": ai_score_threshold
        }

        # Send a POST request to the endpoint
        response = requests.post(url, json=input_data)

        # Check the response status
        if response.status_code == 200:
            result = response.json()
            # Display the result as normal text
            classification = result.get("classification", "N/A")
            st.write("**Classification Result:**")
            st.write(f"Classification: {classification}")

            if classification == "AI Generated Text":
                # Show the toxicity threshold slider
                threshold = st.slider("Toxicity Threshold", 0.0, 1.0, 0.5)
                # Define the input data for toxicity prediction
                input_data["threshold"] = threshold
                # Send a POST request to the endpoint with the updated data
                response = requests.post(url, json=input_data)

                # Check the response status
                if response.status_code == 200:
                    result = response.json()
                    probability_of_toxicity = result.get("probability_of_toxicity", "N/A")
                    prediction = result.get("prediction", "N/A")

                    st.write(f"Probability of Toxicity: {probability_of_toxicity}")
                    st.write(f"Prediction: {prediction}")
                else:
                    st.error("Error: Unable to classify the text for toxicity. Please try again later.")
        else:
            st.error("Error: Unable to classify the text. Please try again later.")
    else:
        st.warning("Please enter some text to classify.")
